### ISSUE TITLE
Coverlet.msbuild not working

### ISSUE THREAD

**Issue by david-77** [tonerdo/coverlet#417]
Hi,

I have a xunit 2.4.1 test project  (.net core 2.2) and able to get coverage report when i use coverlet console command. But I want to make it work with "dotnet test" command, and I fail at it.
Before testing, I typed the "dotnet add package coverlet.msbuild" in the unit tests project's root directory, I think i have a correct log (csproj is updated correctly as followed) :

```
PS C:\Repos\Services\AService.Tests> dotnet add package coverlet.msbuild
  Writing C:\Users\xxxxxx\AppData\Local\Temp\tmp73F8.tmp
info : Ajout de PackageReference pour le package 'coverlet.msbuild' dans le projet 'C:\Repos\Services\AService.Tests\AService.Tests.csproj'.
log  : Persisting no-op dg to C:\Repos\Services\AService.Tests\obj\AService.Tests.csproj.nuget.dgspec.json
info : Restauration des packages pour C:\Repos\Services\AService.Tests\AService.Tests.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/coverlet.msbuild/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/coverlet.msbuild/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/coverlet.msbuild/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/coverlet.msbuild/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/coverlet.msbuild/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/coverlet.msbuild/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/coverlet.msbuild/index.json
info :   NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/coverlet.msbuild/index.json 1673 ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/coverlet.msbuild/index.json 1664 ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/coverlet.msbuild/index.json 1681 ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/coverlet.msbuild/index.json 1748 ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/coverlet.msbuild/index.json 1677 ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/coverlet.msbuild/index.json 1668 ms
info : Le package 'coverlet.msbuild' est compatible avec tous les frameworks spécifiés dans le projet 'C:\Repos\Services\AService.Tests\AService.Tests.csproj'.
info : PackageReference pour le package 'coverlet.msbuild' version '2.6.1' mis à jour dans le fichier 'C:\Repos\Services\AService.Tests\AService.Tests.csproj'.
info : Validation de la restauration...
info : Le fichier d'actifs n'a pas changé. Écriture du fichier d'actifs ignorée. Chemin : C:\Repos\Services\AService.Tests\obj\project.assets.json
log  : Restauration effectuée dans 2,22 sec pour C:\Repos\Services\AService.Tests\AService.Tests.csproj.
```

Then I simply typed :

`dotnet test AService.Tests.csproj /p:CollectCoveragessdf=true`

The test are running, but nothing on coverage, and clearly nothing in relation whith coverlet appears in the log.

Thanks for your help ;)

**Comment by MarcoRossignoli** [comment]
If you don't get error(I'm not french but I see only info and seems ok) maybe commandline is not correct, I see `/p:CollectCoveragessdf=true` and should be `/p:CollectCoverage=true` 
Tell if it help!

**Comment by david-77** [comment]
Thanks for the message. It was just one last test to check if the dotnet test command would verify if the parameter was correct. But the command didn't care of this parameter, either wrong or right, confirming coverlet is not called by the command.

**Comment by MarcoRossignoli** [comment]
`dotnet test` doesn't know about coverlet, we inject custom target and instrumentation will be triggered by `CollectCoverage=true` prop https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild.tasks/coverlet.msbuild.targets#L8
Default is false https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild.tasks/coverlet.msbuild.props#L3

Can you provide simple repro or simple steps to reproduce your issue?

**Comment by david-77** [comment]
Thanks for your help, it's complicated to communicate a sample of the code right now. So I give you the steps I realised.
It's have a .net core 2.2 application using Xunit 2.4.1.
I open the project in Visual Code, and open the terminal view. I go to the project's root directory "cd Repos\Services\AService.Tests" and then I submit the following command :
`PS C:\Repos\NeoGO\PM_M_Service\PM_M_Service.Tests> dotnet add package coverlet.msbuild`

and as i said before is seems to work, my csproj has been modified with these new lines : 
```
<ItemGroup>
     <PackageReference Include="coverlet.msbuild" Version="2.6.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    [ ...... ]
  </ItemGroup>
```

Then I type
`dotnet test /p:CollectCoverage=true`

But no trace of coverlet execution, no coverlet output, just executing tests....

**Comment by MarcoRossignoli** [comment]
@david-77 can you try to produce verbose logging to understand well what's happening https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration

**Comment by MarcoRossignoli** [comment]
@david-77 any news?

**Comment by david-77** [comment]
Hi Marco,

Thank you for asking for news.
Sorry I did not have enough time to try the verdbose loging with my tests.
I hope coming back next week with some news.

**Comment by MarcoRossignoli** [comment]
Meantime we also released a new version and added new way to consume Coverlet throught vstest collector!Take a look at guide!

**Comment by MarcoRossignoli** [comment]
@david-77 any news?
Feel free to close if resolved.

**Comment by david-77** [comment]
Hello Maro, 


Really sorry I totally forgot this. 

In fact it's not resolved yet, i'll give it another try soon. 


Thanks again for your job ;) 


----- Mail original -----

De: "Marco Rossignoli" <notifications@github.com> 
À: "tonerdo/coverlet" <coverlet@noreply.github.com> 
Cc: "david-77" <david.dosantos@free.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 20 Septembre 2019 15:07:23 
Objet: Re: [tonerdo/coverlet] Coverlet.msbuild not working (#417) 


@david-77 any news? 
Feel free to close if resolved.

**Comment by MarcoRossignoli** [comment]
@david-77 news?

**Comment by MarcoRossignoli** [comment]
close for stale conversation, feel free to re-open if needed.
